import Head from "next/head";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useLayoutEffect, useRef } from "react";

if (typeof window !== undefined) gsap.registerPlugin(ScrollTrigger);

export default function Home() {
  const comp = useRef<HTMLElement>(null); // create a ref for the root level element (for scoping)
  const box = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    let ctx = gsap.context((self) => {
      console.log(box.current);
      if (box.current) {
        gsap.to(box.current, {
          x: 500,
          scrollTrigger: {
            trigger: box.current,
            start: "top 80%",
            end: "bottom 20%",
          },
        });
      }
    }, comp);

    return () => ctx.revert();
  }, []);

  return (
    <div className="flex h-screen flex-col">
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="h-[8vh]" />
      <main ref={comp} className="hide-scrollbar h-[92vh]">
        <div className="h-full bg-red-200"></div>
        <div className="h-full section-2 bg-green-200">
          <div
            ref={box}
            className="box bg-black h-10 w-10 relative top-48"
          ></div>
        </div>
        <div className="h-full bg-blue-200"></div>
      </main>
    </div>
  );
}
