import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="flex h-screen flex-col">
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="h-[8vh]" />
      <div className="hide-scrollbar md:scroll-snap-container flex flex-1 flex-col overflow-x-hidden overflow-y-scroll">
        <main>
          <div className="scroll-snap-align-start h-[92vh] bg-red-200"></div>
          <div className="scroll-snap-align-start h-[92vh] bg-green-200"></div>
          <div className="scroll-snap-align-start h-[92vh] bg-blue-200"></div>
        </main>
      </div>
    </div>
  );
}
