import Head from "next/head";

import { motion } from "framer-motion";

import { useEffect, useState } from "react";
import Image from "next/image";

import logo from "public/logo.png";
import image from "public/image.webp";

export default function Home() {
  return (
    <div className="flex h-screen flex-col">
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="h-[10vh] bg-yellow-400" />
      <main className="hide-scrollbar scroll-snap-container flex flex-1 flex-col overflow-x-hidden overflow-y-scroll">
        <div className="scroll-snap-align-start min-h-[90vh] flex flex-col items-center justify-center  bg-red-300">
          <h1 className="flex min-w-[100%] justify-center gap-4 text-center text-3xl md:text-7xl">
            <motion.div
              initial={{ opacity: 0, x: "80vh" }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 1, ease: "easeInOut" }}
              className="font-black text-[#30315B]"
            >
              Some
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: "80vh" }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 1, ease: "easeInOut", delay: 0.5 }}
              className="font-normal text-[#30315B]"
            >
              Random
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: "80vh" }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 1, ease: "easeInOut", delay: 1 }}
              className="font-light text-[#0d8e77]"
            >
              Slogan.
            </motion.div>
          </h1>
        </div>
        {/* <div className="scroll-snap-align-start min-h-[90vh] bg-purple-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-orange-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-purple-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-orange-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-purple-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-orange-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-purple-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-orange-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-purple-300"></div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-orange-300"></div> */}
        <div className="scroll-snap-align-start min-h-[90vh] bg-purple-300">
          <Image src="/image.webp" alt="asd" className="w-auto" width={1000} height={1000}/>
        </div><div className="scroll-snap-align-start min-h-[90vh] bg-purple-300">
          <Image src="/hedg-mock.png" alt="asd" className="w-auto" width={1000} height={1000}/>
        </div><div className="scroll-snap-align-start min-h-[90vh] bg-purple-300">
          <Image src="/image.webp" alt="asd" className="w-auto" width={1000} height={1000}/>
        </div><div className="scroll-snap-align-start min-h-[90vh] bg-purple-300">
          <Image src="/insta-logo.png" alt="asd" className="w-auto" width={1000} height={1000}/>
        </div><div className="scroll-snap-align-start min-h-[90vh] bg-purple-300">
          <Image src="/mock-insta.png" alt="asd" className="w-auto" width={1000} height={1000}/>
        </div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-orange-300">
          <Image src={image} alt="asd" className="w-auto" placeholder="blur" />
        </div>
        <div className="scroll-snap-align-start min-h-[90vh] bg-red-300">
          <Image src={image} alt="asd" className="w-auto" placeholder="blur" />
        </div>
      </main>
    </div>
  );
}
